### PR TITLE
Wallpaper for all desktops

### PR DESCRIPTION
**Pull request by K-Mazur**
Added a small update for changing the wallpaper for all desktops instead of just one.

### CODE REVIEW

**Comment by bensleveritt** [comment]
I can't test this right now, but it looks like it would work, so I'll accept it and test it as part of the next release.

Thanks for your contribution!

**Comment by PatrickF1** [comment]
I tried it and it only changed the wallpaper for one desktop :(

**Comment by K-Mazur** [comment]
Hmm, strange. It's changing the wallpaper in all of my desktops. Monterey M1 MAX

**Comment by PatrickF1** [comment]
I'm on Monterey as well but still on a 2019 i7 laptop (though I doubt the hardware really matters). To repro, what I did was I created a new desktop space and ran the command and saw that only the current desktop space updates its wallpaper.

**Comment by K-Mazur** [comment]
Ok, I can confirm that @PatrickF1. I've just created a new desktop space with Mission Control. The command didn't change the wallpaper on the new desktop space. It looks like the code works, but only for physical displays. The wallpaper on all my physical displays gets updated.

**Comment by YohannParis** [comment]
I agree, I have the latest version, and `m wallpaper` only update the current desktop.

**Pull request merged**
