### PR TITLE
Use more native bash for `dns flush`

### PR DESCRIPTION
**Pull request by n8felton**
This update allows for the `dns flush` command to use more native bash for the if statements, resulting in cleaner, more efficient code.

### CODE REVIEW

**Comment by rgcr** [comment]
Hello @n8felton, than you so much for this and for the time you spent on it 👍.

- I think is not a good idea just  compare the minor and patch versions, what happens if in a future the major version changes to 11 and there is another way to do it, I mean this is an extreme case but It can happens.  I would like to hear your opinion :)

- I don't see the `hardware` plugin in the commit I only see the autocompletions :(

**Comment by n8felton** [comment]
You bring up a good point. I will post an update that should help with that.

Sorry about bd98864, I forgot that if I pushed to my master branch it would update the PR. I have removed that commit for now until it is more complete.

**Comment by doodzik** [comment]
@rgcr This pr is now quite old. I think we should merge or discard it, but not let it sit around idle.

**Comment by rgcr** [comment]
You are right, I think the current version is ok and doesn't need to be changed, thanks all for your contributions.

**Pull request closed without merging**
