### PR TITLE
Added additional functionalities to itunes script

### PR DESCRIPTION
**Pull request by japorized**
- added get player state
- added get song progress
- added get repeat status
- added set repeat mode
- added toggle for shuffle

Changed help message to be more succinct

### CODE REVIEW

**Comment by japorized** [comment]
Decided to add a few more of the available controls. The original motivation is to make my tinkering with chunkwm and shkd a lot easier, but hopefully others may find it useful/helpful.

**Comment by rgcr** [comment]
Thank you so much  👍

**Comment by rgcr** [comment]
@japorized Please help to add the completions for the new functionalities

**Comment by rgcr** [comment]
Please help to add the completions for the new functionalities and creates new PR for this such good improvement.

**Comment by japorized** [comment]
Oh, that's my bad for forgetting about that. I'll put in a new PR.

**Pull request merged**
