### PR TITLE
Added localhost plugin

### PR DESCRIPTION
**Pull request by gmhabchi**
Just added a simple plugin to view, add and remove items from the hosts file under /etc/hosts

### CODE REVIEW

**Comment by bensleveritt** [comment]
Any chance you could add the completions too?

**Comment by rgcr** [comment]
Thank you for this but please add the completions in order to merge your PR.

**Comment by gmhabchi** [comment]
oops, added them :)

**Comment by rgcr** [comment]
One last thing, please help me to add the help info in the `README.md` file

**Pull request merged**
