### PR TITLE
change shebang

### PR DESCRIPTION
**Pull request by doodzik**
the rational behind this can be found [here](http://stackoverflow.com/a/10383546)

### CODE REVIEW

**Comment by rgcr** [comment]
Hello @doodzik, thank you so much for this but I prefer `sh(Bourne shell)` over `bash` because I think it is more portable across POSIX systems even if they happen not to have `bash`, they are required to have `sh`

**Comment by doodzik** [comment]
Normally I would be on your side of the argument, but this project is specifically targeted at macOS.
So we don't need to have portabillity across POSIX systems.
This means that we can leverage the additional features that bash has.

**Comment by rgcr** [comment]
@doodzik You are right it's a mac tool but I think it's an unnecessary change, I mean can you tell me what kind of feature we can use with `bash` that we can't do it with a POSIX script ?

**Comment by doodzik** [comment]
Regex matching
Associative arrays -> multidimensional arrays
Better io redirection
Process substitution
Brace expansion
Local variables

**Comment by rgcr** [comment]
* **Regex matching**
  We can use   `echo "" | grep -E 'REGEX'` instead

* **Associative arrays  _(do we need that?)_**
  We can use a simple `awk` or `sh` array, if we need something too complex we can use other scripting language like `python` or `perl`

* **Better io redirection _(what do you mean? )_**
  The `POSIX` redirections seem ok for me

* **Process substitution**
   We can use a simple pipe `|` or a subshell `$()`.  [Example](https://github.com/rgcr/m-cli/blob/master/plugins/network#L19)

* **Brace expansion**
  I don't see a good utility for this

* **Local variables**
  This is the most convincing but I think with good practices and being careful it is not a big deal

**Comment by mafrosis** [comment]
I would always choose the more expressive language, if there's no reason to use the lesser.

**Comment by doodzik** [comment]
Redirection: That we can redirect stdout and stderr at the same time with `&>`. This is just a little niceness, but nothing to change the interpreter for. The commutation of the features makes the difference.

Sure we can do it the way you described, but as I mentioned earlier. We work on a system that comes with bash preinstalled and which uses bash as its default shell.
Which means that a lot of people will know bash and not necessarily sh.

Which benefit do we have from constraining ourselves by using sh in this case?

**Comment by rgcr** [comment]
`2>&1`  => `&>`

I think there are not any benefits just the restriction to develop in a POSIX way _(sorry but I'm a little bit picky with this)_ 😄 But I agree with you, lets change this and see what happens.

**Comment by doodzik** [comment]
Nothing to be sorry about ;)

cool :)

**Pull request merged**
