### PR TITLE
adding bash and zsh completions

### LINKED ISSUE #14: feature request: autocomplete

### PR DESCRIPTION
**Pull request by yazgazan**
Adding a completion script for bash and zsh.

Fixes #14

### CODE REVIEW

**Comment by rgcr** [comment]
Thats really awesome 👍  
But I tested it and seems it is not working, at least in my env, did you test it? 

I tested it adding `_m` in `/usr/local/share/zsh/site-functions` and reloaded my terminal

**Comment by yazgazan** [comment]
Sorry, I was sourcing it for quick testing ... My last commit should fix it.

**Comment by rgcr** [comment]
@yazgazan, I think bash completion is not working also :(

**Comment by yazgazan** [comment]
Do you source the completion/bash/m file ? For some reasons unknown to me, bash doesn't source the files in /usr/local/etc/bash_completion.d ...

**Comment by rgcr** [comment]
@yazgazan, Yes I moved the file to the bash completion directory, let me test it again 👍

**Comment by yazgazan** [comment]
An alternative solution to sourcing the file would be to install bash-completion using homebrew. (bash-completion sources every files in /usr/local/etc/bash_completion.d)

**Comment by rgcr** [comment]
Thanks a lot for this, you really did a great work here 👍  I tested both completions and they are working properly. Also I've included completion for newest plugins like vpn, dns.

**Comment by contra** [comment]
Might have to PR a fish shell autocomplete unless anyone made one already

**Comment by rgcr** [comment]
Please feel free to contribute, It will be very useful, and sorry but I'm not very familiar with fish :)

**Pull request merged**
